### PR TITLE
LOG-9309 removed deprecated commands and related code

### PR DESCRIPTION
**Pull request by stopal-r7**
Remove deprecated commands and unit tests from code base.

### CODE REVIEW

**Comment by ellynch-r7** [comment]
Looks good.

Is there any documentation that needs to be updated?

**Comment by stopal-r7** [comment]
@ellynch-r7 there was no mention of deprecated commands in readme.md so I put an entry on CHANGES.txt only.

**Review by ellynch-r7 — APPROVED** [review]

**Comment by ellynch-r7** [comment]
LGTM

Just another thought - do support need a heads up about this?

**Review by danilosterrapid7 — APPROVED** [review]

**Comment by stopal-r7** [comment]
@ellynch-r7 yeah, they are aware, thanks!

**Pull request merged**
