### PR TITLE
init_config if config file does not exist

### PR DESCRIPTION
**Pull request by stopal-r7**
@StephenHynes7 @eflanagan-r7 @cheffernan-r7 @fk92r7 

this solves the appdirs dependency on installation and we are not hitting pypi wheels data_files bug anymore: https://bitbucket.org/pypa/wheel/issues/92

### CODE REVIEW

**Comment by fk92r7** [comment]
👍 Looks good to me.

**Comment by StephenHynes7** [comment]
LGTM did you update the readme to reflect the `last` change

**Comment by eflanagan-r7** [comment]
+1

**Comment by stopal-r7** [comment]
@StephenHynes7 nice reminder, will do.

**Comment by StephenHynes7** [comment]
+1

**Pull request merged**
