### PR TITLE
adds default for mgmt url and uses method in all mgmt calls

### PR DESCRIPTION
**Pull request by pquinn-r7**
Use the get_management_url method so users will be able to set own url in config for all mgmt calls

### CODE REVIEW

**Comment by stopal-r7** [comment]
I think we should consider configuring a baseurl instead of a specific sub api in one of the following PRs. This would simplify config file and implementation a lot.

**Review by stopal-r7 — APPROVED** [review]
Looks good.

**Review by ellynch-r7 — APPROVED** [review]
Looks good!

**Comment by ellynch-r7** [comment]
Actually, you might want to bump the version number!

**Review by scawley-r7 — APPROVED** [review]

**Comment by pquinn-r7** [comment]
@ellynch-r7 bumped the version there

**Pull request merged**
